### PR TITLE
Switch from Analytics package to new Analytics.CSharp package

### PR DESCRIPTION
**Pull request by tombogle**
This fixes deadlock bug properly. This needs to be checked carefully to make sure all the correct properties are coming through in the same way (or that we're okay with any changes). The interfaces changed quite a bit.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
It all looks plausible but I don't understand what it's all about very well. A few suggestions that might be some use.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-:-NMZCd4N7_ngLtIhq9zv:b-g60b85)* status: all files reviewed, 7 unresolved discussions (waiting on @hatton, @jasonleenaylor, and @tombogle)

___
*[`src/DesktopAnalytics/Analytics.cs` line 40 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZBwki7n8QnZztPJFY:-NMZBwki7n8QnZztPJFZ:b-54cjk8) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L40)):*
> ```Smalltalk
> 		private const string kUserConfigFileName = "user.config";
> 
> 		private static JsonObject _locationInfo;
> ```

I think a brief explanation of what you're getting at with this variable would help. Most of what gets added to it is also added to _propertiesThatGoWithEveryEvent, so why distinguish location properties?
___
*[`src/DesktopAnalytics/Analytics.cs` line 50 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZ8WOo25hS3x66A1w8:-NMZ8WOo25hS3x66A1w9:b15p3m5) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L50)):*
> ```Smalltalk
> 		public delegate void ExceptionHandlerDelegate(Exception exception);
> 
> 		public event ExceptionHandlerDelegate AnalyticsExceptionThrown;
> ```

New public event might deserve a comment
___
*[`src/DesktopAnalytics/Analytics.cs` line 445 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZBYlp1t7bjzu_pjHv:-NMZBYlp1t7bjzu_pjHw:bcuaj7a) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L445)):*
> ```Smalltalk
> 							{
> 								Debug.WriteLine($"DesktopAnalytics: external ip = {result}");
> 								_locationInfo.Add("ip", result);
> ```

It's not obvious why ip is considered a location property.
___
*[`src/DesktopAnalytics/Analytics.cs` line 598 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZ7tiT3MRXyroqFT18:-NMZ7tiT3MRXyroqFT19:bwar7u) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L598)):*
> ```Smalltalk
> 		}
> 
> 		public void OnExceptionThrown(Exception e)
> ```

Nothing appears to call this new method. Is it a required callback that allows this object to implement an interface that the new version of Analytics requires? Would it ever be appropriate for a client of DesktopAnalytics to call it directly? I think some sort of comment might be helpful.
___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZ8qIGEHRqy-R1U2qA:-NMZ8qIGEHRqy-R1U2qB:b7t8zfm) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L5)):*
> ```Smalltalk
> namespace DesktopAnalytics
> {
> 	public class StatisticsMonitor : Plugin
> ```

I think a class comment might be helpful. This is not just monitoring any statistics, it has a fairly specific purpose, but that purpose is unclear, especially since some of the properties are never set here, yet don't have public setters. I'm guessing Plugin is a base class or interface that CSharp.Analytics promises to call in a particular way, but it's not obvious. Why, for example, do we need code to maintain Succeeded and Failed, but not to maintain Submitted?
___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZARHs2j6HJx_cfatz:-NMZARHs2j6HJx_cfau-:b-22mxgw) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L14)):*
> ```Smalltalk
> 		internal void NoteFailures()
> 		{
> 			Failed += Outstanding;
> ```

How do we know that an exception thrown will cause all events that have been submitted and not succeeded to fail?
Are there threading issues here? Could it be that another thread is in the process of submitting another report? Why do we need a lock for adjusting Succeeded but not for this?
___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZAwSL4-EhUtjNhU46:-NMZAwSL4-EhUtjNhU47:b43voh4) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L23)):*
> ```Smalltalk
> 			if (incomingEvent.type != "identify")
> 			{
> 				lock (this)
> ```

It's usually considered best practice (for avoiding deadlocks, I think) to lock on a private object rather than on 'this', which code we don't control could also lock.

**Review by tombogle — COMMENTED** [review]
Thanks. Unfortunately, I'm getting back around to looking at this after it has sat languishing for a long time, so I'm more than a little rusty on it myself. I had to go back to the online documents for Analytics-CSharp to refresh my memory.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-:-NMZOqJl-NlCjWD1Hp3i:bdbcd91)* status: all files reviewed, 7 unresolved discussions (waiting on @hatton, @jasonleenaylor, and @JohnThomson)

___
*[`src/DesktopAnalytics/Analytics.cs` line 40 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZBwki7n8QnZztPJFY:-NMZRlq59k-AoVXuPni-:b-l4396t) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think a brief explanation of what you're getting at with this variable would help. Most of what gets added to it is also added to _propertiesThatGoWithEveryEvent, so why distinguish location properties?
</blockquote></details>

Added a comment
___
*[`src/DesktopAnalytics/Analytics.cs` line 50 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZ8WOo25hS3x66A1w8:-NMZT3phEDZTvLulI4EL:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L50)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

New public event might deserve a comment
</blockquote></details>

Done.
___
*[`src/DesktopAnalytics/Analytics.cs` line 445 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZBYlp1t7bjzu_pjHv:-NMZT5OcA-Ic8VSan9Po:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L445)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious why ip is considered a location property.
</blockquote></details>

Done.
___
*[`src/DesktopAnalytics/Analytics.cs` line 598 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZ7tiT3MRXyroqFT18:-NMZOkjv0VsaqNYDu2Ta:brpq7lw) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/Analytics.cs#L598)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Nothing appears to call this new method. Is it a required callback that allows this object to implement an interface that the new version of Analytics requires? Would it ever be appropriate for a client of DesktopAnalytics to call it directly? I think some sort of comment might be helpful.
</blockquote></details>

Wrapped in #region ICoroutineExceptionHandler implementation
___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZ8qIGEHRqy-R1U2qA:-NMZYcHMAEFhDPojBZjq:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L5)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think a class comment might be helpful. This is not just monitoring any statistics, it has a fairly specific purpose, but that purpose is unclear, especially since some of the properties are never set here, yet don't have public setters. I'm guessing Plugin is a base class or interface that CSharp.Analytics promises to call in a particular way, but it's not obvious. Why, for example, do we need code to maintain Succeeded and Failed, but not to maintain Submitted?
</blockquote></details>

Done.
___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZARHs2j6HJx_cfatz:-NMZZOGX1OzBtEihhHEC:bxzf7zx) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L14)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How do we know that an exception thrown will cause all events that have been submitted and not succeeded to fail?
Are there threading issues here? Could it be that another thread is in the process of submitting another report? Why do we need a lock for adjusting Succeeded but not for this?
</blockquote></details>

I think you're right about wanting a lock here, so I have added it. I don't know if we can be 100% sure that anything outstanding has failed, since perhaps a momentary hiccup could possibly cause one event to fail but allow the next one in the queue to succeed. I suspect that's going to be extraordinarily rare. Anyway, this class exists primarily for the purpose of testing with the sample apps. Not sure how likely our real-world apps will be to want to keep track of stats. Looking at this, I'm kind of thinking that maybe we should also make Submitted a private setting and use a method that guarantees we get a lock before changing it also, since the value of Outstanding will not be thread-safe as it is. Does that sound right to you? 
___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZAwSL4-EhUtjNhU46:-NMZaJvrBPWiZ_qzuSdn:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L23)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Yes, this is accurate. A private locking object in this class would be better.
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
Sorry. I only saw the notice requesting my review today.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-:-NMZeUjU2Sruu4cdVoRi:b1vfllr)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton and @jasonleenaylor)

___
*[`src/DesktopAnalytics/StatisticsMonitor.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NMZAwSL4-EhUtjNhU46:-NMZeHpQ06FasScBZMuc:b-zhcsij) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/5eb06ab25af87e14b994d25b4a2ec1fa30237340/src/DesktopAnalytics/StatisticsMonitor.cs#L23)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still seeing lock(this). Did something not get committed? (Also the new lock above)

**Comment by tombogle** [comment]
Sorry, that change didn't make it in. It's there now. (I only just requested your review today because it had been sitting for a long time unreviewed by the others I had requested. Because of @hatton 's history with this library, I would really want him to review it, but I know he doesn't come up for air very often.)

**Review by JohnThomson — COMMENTED** [review]
:lgtm:. But yes, it would be better if someone more familiar with this code base could review. (I don't understand why, but Reviewable won't let me approve this.)

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-:-NM_TCbF2pOB5mmsN6Ed:b-ws4sq0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton and @jasonleenaylor)

**Review by JohnThomson — APPROVED** [review]
A couple of minor points, but the changes looks reasonable. I don't really think I know this code well enough, or know what changed in the dependencies well enough, to feel as confident as I would like if I am the main approver. However, in case you need someone to approve it and can't find anyone better qualified, I've gone ahead.
:lgtm:

> Reviewed 1 of 6 files at r4, 1 of 6 files at r5, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-:-NfAXeykD-KGriabZYnp:b-qe94o8)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @tombogle)

___
*[`src/DesktopAnalytics/Analytics.cs` line 418 at r6](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NfAV0hI49tPYssEvgb4:-NfAV0hI49tPYssEvgb5:b-gov6e4) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/27987f6f040026931b5d30c04e84440c2740af92/src/DesktopAnalytics/Analytics.cs#L418)):*
> ```Smalltalk
> 				try
> 				{
> 					bool json = string.IsNullOrEmpty(UrlThatReturnsExternalIpAddress);
> ```

It's not a new problem, but the very poor name of this variable makes reading the subsequent code difficult. Wants to be something like "cantGetIpAddress"
___
*[`src/DesktopAnalytics/Analytics.cs` line 594 at r6](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NfAVws2EP_vuPklYNZS:-NfAVws2EP_vuPklYNZT:b-e5jffs) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/27987f6f040026931b5d30c04e84440c2740af92/src/DesktopAnalytics/Analytics.cs#L594)):*
> ```Smalltalk
> 		public void Dispose()
> 		{
> 			Client?.ShutDown();
> ```

It's a little surprising that we don't do something about _singleton. Seems reasonable that once we've disposed of (presumably) the singleton, we could start over if we wanted, though maybe no one does? At least, would setting it to null cause us to fail faster or more clearly if anyone still tries to send analytics?
___
*[`src/DesktopAnalytics/Properties/AssemblyInfo1.cs` line 20 at r6](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NfAXJA-8mE2bFkod8Oe:-NfAXJA-8mE2bFkod8Of:bg6dcw4) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/27987f6f040026931b5d30c04e84440c2740af92/src/DesktopAnalytics/Properties/AssemblyInfo1.cs#L20)):*
> ```Smalltalk
> [assembly: Guid("435b8947-aafd-45b8-8c2c-19104e3990f4")]
> 
> [assembly: InternalsVisibleTo("DesktopAnalyticsTests, PublicKey=00240000048000009400000006020000002400005253413100040000010001008339b2ae1bf006934f6176dec6ea2a8a7d67383613dcb03d71975e7b05ad546562c84529a4811e94c889e55f2532d1a90baaf20be9bff39ac6f5365bd605d70b90489840b7ba6d1c231b0e550c4abe4f60553856ef142a40a91e53d56e79f69dc79c4e95817de498aac924ee011f03b4e1c1d772d51c4946c1185e3bfb621bc6")]
> ```

Will something maintain this somehow? Otherwise, it seems unfortunate that it is hard-coded that only one exact build of tests can access the internals.

**Comment by tombogle** [comment]
*[`src/DesktopAnalytics/Analytics.cs` line 594 at r6](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NfAVws2EP_vuPklYNZS:-NfCMIjD8DlHfzAUC0g-:bgudo1e) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/27987f6f040026931b5d30c04e84440c2740af92/src/DesktopAnalytics/Analytics.cs#L594)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a little surprising that we don't do something about _singleton. Seems reasonable that once we've disposed of (presumably) the singleton, we could start over if we wanted, though maybe no one does? At least, would setting it to null cause us to fail faster or more clearly if anyone still tries to send analytics?
</blockquote></details>

Not sure whether it would actually work to try to restart. I see that we check in the constructor to make sure that the singleton is null and throw an exception if not, so that should result in an adequately fast failure. If we were to set it null in Dispose and we really can't restart, then it might fail in a less predictable or understandable way. At least until someone comes up with a scenario where restarting seems desirable and logical, I'm inclined to leave it as is. At least the intended use is clear as it is.

**Comment by tombogle** [comment]
*[`src/DesktopAnalytics/Analytics.cs` line 418 at r6](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NfAV0hI49tPYssEvgb4:-NfCPGkI1U0yknv0N5aV:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/27987f6f040026931b5d30c04e84440c2740af92/src/DesktopAnalytics/Analytics.cs#L418)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not a new problem, but the very poor name of this variable makes reading the subsequent code difficult. Wants to be something like "cantGetIpAddress"
</blockquote></details>

Done.

**Comment by tombogle** [comment]
*[`src/DesktopAnalytics/Properties/AssemblyInfo1.cs` line 20 at r6](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/29#-NfAXJA-8mE2bFkod8Oe:-NfCV1Rc62OVlVOA11gP:bwvyox4) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/27987f6f040026931b5d30c04e84440c2740af92/src/DesktopAnalytics/Properties/AssemblyInfo1.cs#L20)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Will something maintain this somehow? Otherwise, it seems unfortunate that it is hard-coded that only one exact build of tests can access the internals.
</blockquote></details>

Reverted

**Pull request merged**
