### PR TITLE
BL-12617 Add host param so we can send events through blorg

### PR DESCRIPTION
**Pull request by nabalone**
BL-12617 to send events through bloomlibrary.org instead of directly to segment

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
I wasn't sure what to do about the interface used by both Segment and Mixpanel. Is there a better way to organize this?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-:-Nc4PAt54GXJwRyauCp5:b-ebxf8)* status: 0 of 4 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/DesktopAnalytics/Analytics.cs` line 87 at r1](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-Nc4ga3e75dN0ABJxQoK:-Nc4ga3e75dN0ABJxQoL:b-oh3jcq) ([raw file](https://github.com/sillsdev/DesktopAnalytics.net/blob/59ee01852c17b8ee7d77cb469aab3b5e909d7b9b/src/DesktopAnalytics/Analytics.cs#L87)):*
> ```Smalltalk
> 		/// <param name="retainPii">If false, userInfo will be stripped/hashed/adjusted to prevent communication of
> 		/// personally identifiable information to the analytics server.</param>
> 		/// <param name="clientType"></param>
> ```

Sorry, it's probably just a personal pet peeve, but I don't like empty/useless <param>s.
Let's remove it or make it something like `See ClientType` (with the special magic which links over to that enum).
___
*[`src/DesktopAnalytics/Analytics.cs` line 88 at r1](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-Nc4gtwd9DnYYeVXIvUf:-Nc4gtwd9DnYYeVXIvUg:b-44b2sc) ([raw file](https://github.com/sillsdev/DesktopAnalytics.net/blob/59ee01852c17b8ee7d77cb469aab3b5e909d7b9b/src/DesktopAnalytics/Analytics.cs#L88)):*
> ```Smalltalk
> 		/// personally identifiable information to the analytics server.</param>
> 		/// <param name="clientType"></param>
> 		/// <param name="host">For SegmentClient only, the url of the host to send analytics to</param>
> ```

How about something like
`The url of the host to send analytics to. Will use the client's default if not provided. Throws an ArgumentException if the client does not support setting the host.`
?
___
*[`src/DesktopAnalytics/Analytics.cs` line 110 at r1](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-Nc4f_g92NFIAALN5jxm:-Nc4f_g92NFIAALN5jxn:bo1arz3) ([raw file](https://github.com/sillsdev/DesktopAnalytics.net/blob/59ee01852c17b8ee7d77cb469aab3b5e909d7b9b/src/DesktopAnalytics/Analytics.cs#L110)):*
> ```Smalltalk
>                             throw new ArgumentException("MixpanelClient does not currently support a host parameter");
>                         }
>                         Client = new MixpanelClient();
> ```

Mix of indentation types (space and tab) introduced here...

But I think I would just let the ArgumentException be thrown by Initialize. That keeps implementation-specific logic out of this class.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/DesktopAnalytics/Analytics.cs` line 87 at r1](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-Nc4ga3e75dN0ABJxQoK:-Nc8oXGT8lr6H40yoBti:b-896fix) ([raw file](https://github.com/sillsdev/DesktopAnalytics.net/blob/59ee01852c17b8ee7d77cb469aab3b5e909d7b9b/src/DesktopAnalytics/Analytics.cs#L87)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, it's probably just a personal pet peeve, but I don't like empty/useless <param>s.
Let's remove it or make it something like `See ClientType` (with the special magic which links over to that enum).
</blockquote></details>

Done.
___
*[`src/DesktopAnalytics/Analytics.cs` line 88 at r1](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-Nc4gtwd9DnYYeVXIvUf:-Nc8ogZK8S_4XYvvGwoJ:b-85nsn5) ([raw file](https://github.com/sillsdev/DesktopAnalytics.net/blob/59ee01852c17b8ee7d77cb469aab3b5e909d7b9b/src/DesktopAnalytics/Analytics.cs#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How about something like
`The url of the host to send analytics to. Will use the client's default if not provided. Throws an ArgumentException if the client does not support setting the host.`
?
</blockquote></details>

That's much better. Done.
___
*[`src/DesktopAnalytics/Analytics.cs` line 110 at r1](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-Nc4f_g92NFIAALN5jxm:-Nc8oxz8CRHIk9W303gX:b-896fix) ([raw file](https://github.com/sillsdev/DesktopAnalytics.net/blob/59ee01852c17b8ee7d77cb469aab3b5e909d7b9b/src/DesktopAnalytics/Analytics.cs#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Mix of indentation types (space and tab) introduced here...

But I think I would just let the ArgumentException be thrown by Initialize. That keeps implementation-specific logic out of this class.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Review by andrew-polk — APPROVED** [review]
@jasonleenaylor or @tombogle want to take a look?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/DesktopAnalytics.net/31#-:-Nc9XidbDZ2FAXJKb3j_:b-94y5w2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
