### PR TITLE
Prevent Flush from deadlocking

### PR DESCRIPTION
**Pull request by tombogle**
Also upgraded to latest version of Segment's Analytics package
Misc code cleanup in Analytics.cs

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27)

### CODE REVIEW

**Comment by tombogle** [comment]
This "fix" is a kludge. I have reported the problem to Segment in hopes of a fix: https://github.com/segmentio/Analytics.NET/issues/200

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27)* status: all files reviewed, 4 unresolved discussions (waiting on @jasonleenaylor and @tombogle)

___
*[`SampleAppWithForm/Form1.cs` line 31 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8uDpCF51-SU1G-p0:-N9D8uDpCF51-SU1G-p1:b-g15la4) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/SampleAppWithForm/Form1.cs#L31)):*
> ```Smalltalk
> 				$"Submitted: {Segment.Analytics.Client.Statistics.Submitted}; " +
> 				$"Failed:  {Segment.Analytics.Client.Statistics.Failed}");
> 			// This allows us to illustrate the deadlock problem.
> ```

Want to reference an issue and/or the code used to work around it?
___
*[`src/DesktopAnalytics/Analytics.cs` line 578 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8EON0CAfagQxNNMG:-N9D8EON0CAfagQxNNMH:b-4yxmo0) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L578)):*
> ```Smalltalk
> 				// So instead of calling Flush, if there are events in the queue, we just wait a little while.
> 				// The default timeout on the client is 5 seconds, so probably we should never need to wait
> 				// longer than that.
> ```

Want to reference the reported issue here for future reference?
___
*[`src/DesktopAnalytics/Analytics.cs` line 586 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8LIZBIICBfsZFwgd:-N9D8LIZBIICBfsZFwge:b-fiefzm) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L586)):*
> ```Smalltalk
> 						break;
> 					totalWait += 2500;
> 					Thread.Sleep(2500);
> ```

2.5 seconds seems like a long time to wait (I assume the user experiences this as the app taking a long time to close?)
___
*[`src/DesktopAnalytics/Analytics.cs` line 636 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D81sh6Ibsl5PCaTj1:-N9D81sh6Ibsl5PCaTj2:bwy1j6k) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L636)):*
> ```Smalltalk
> 				// helpful if someone starts using an app built before the OS is released. Anything that
> 				// your app has a manifest which says it supports the OS it is running on.  This is not
> 				// After Windows 8 the Environment.OSVersion started misreporting information unless
> ```

This comment got messed up.

**Comment by jasonleenaylor** [comment]
*[`src/DesktopAnalytics/Analytics.cs` line 586 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8LIZBIICBfsZFwgd:-N9DAGA77WRBIa7MgqA6:b-dx4) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L586)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

2.5 seconds seems like a long time to wait (I assume the user experiences this as the app taking a long time to close?)
</blockquote></details>

It seems like a long time, but since it will only happen if the app is closed when events are queued it might be fine.

**Comment by tombogle** [comment]
*[`src/DesktopAnalytics/Analytics.cs` line 586 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8LIZBIICBfsZFwgd:-N9DENSQ3YnMrbgfyGvu:b-t23o03) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L586)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

It seems like a long time, but since it will only happen if the app is closed when events are queued it might be fine.
</blockquote></details>

Added a comment to explain this. (After more experimentation, I determined that it was occasionally possible to end up with a single wait cycle of only a second, so I just decided to make it simple and wait a half second at a time. But most of the time it takes 2-4 seconds.)

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27)* status: 3 of 11 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @jasonleenaylor)

___
*[`src/DesktopAnalytics/Analytics.cs` line 578 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8EON0CAfagQxNNMG:-N9DHS2HDrRQmkjJ-2E6:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L578)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Want to reference the reported issue here for future reference?
</blockquote></details>

Done.
___
*[`src/DesktopAnalytics/Analytics.cs` line 636 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D81sh6Ibsl5PCaTj1:-N9DHN_-EDlfGP5EoOoQ:b-886gsx) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/src/DesktopAnalytics/Analytics.cs#L636)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment got messed up.
</blockquote></details>

Fixed
___
*[`SampleAppWithForm/Form1.cs` line 31 at r1](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27#-N9D8uDpCF51-SU1G-p0:-N9DHSk06dTvfLQT6tKl:b-896fix) ([raw file](https://github.com/sillsdev/desktopanalytics.net/blob/d4e20025e1632f838d56a8e616c13f3a3b0866c3/SampleAppWithForm/Form1.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Want to reference an issue and/or the code used to work around it?
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 6 of 7 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 7 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/desktopanalytics.net/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
